### ISSUE TITLE
hovering on an item (rei) crashed the client (1.20.1)

### ISSUE THREAD

**Issue by ChimeraMusic** [ZsoltMolnarrr/SpellDamage#19]
java.lang.NoClassDefFoundError: net/spell_power/api/attributes/SpellAttributes
	at net.carlo.tctimod.item.custom.CursedNetheriteTopazBelt.getModifiers(CursedNetheriteTopazBelt.java:23)
	at net.minecraft.class_1799.md195799$trinkets$lambda$getTooltip$0$12(class_1799.java:15654)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at net.minecraft.class_1799.handler$ijo000$trinkets$getTooltip(class_1799.java:15620)
	at net.minecraft.class_1799.method_7950(class_1799.java:687)
	at com.anthonyhilyard.prism.item.ItemColors.getColorForItem(ItemColors.java:86)
	at com.anthonyhilyard.legendarytooltips.LegendaryTooltips.getDefinitionColors(LegendaryTooltips.java:96)
	at com.anthonyhilyard.legendarytooltips.LegendaryTooltips.onTooltipColorEvent(LegendaryTooltips.java:241)
	at com.anthonyhilyard.iceberg.events.RenderTooltipEvents.lambda$static$4(RenderTooltipEvents.java:57)
	at net.minecraft.class_332.handler$dno000$iceberg$preFillGradient(class_332.java:3935)
	at net.minecraft.class_332.method_51435(class_332.java:647)
	at me.shedaniel.rei.impl.client.gui.fabric.ScreenOverlayImplFabric.renderTooltipInner(ScreenOverlayImplFabric.java:83)
	at me.shedaniel.rei.impl.client.gui.fabric.ScreenOverlayImplFabric.renderTooltipInner(ScreenOverlayImplFabric.java:75)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderTooltip(ScreenOverlayImpl.java:328)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.lambda$lateRender$3(ScreenOverlayImpl.java:319)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.lateRender(ScreenOverlayImpl.java:319)
	at me.shedaniel.rei.impl.client.registry.screen.ScreenRegistryImpl$5.lateRender(ScreenRegistryImpl.java:384)
	at me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$onApplied$7(DefaultScreenOverlayRenderer.java:118)
	at me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$new$3(DefaultScreenOverlayRenderer.java:71)
	at net.minecraft.class_757.handler$zmi000$architectury$renderScreenPost(class_757.java:15174)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.spell_power.api.attributes.SpellAttributes
	... 28 more

**Comment by ZsoltMolnarrr** [comment]
The mod adding CursedNetheriteTopazBelt is relying on an outdated version of Spell Power attributes.
