### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by A5ho9999** [ZsoltMolnarrr/SpellDamage#22]
Crashes on launch when trying to create a mod.

Mod Version: 0.10.2+1.20.1
Minecraft: 1.20.1
Fabric Loader 0.15.11

Build Configuration:
```
repositories {
	maven { url "https://maven.ladysnake.org/releases" }
	maven { url "https://jitpack.io" }
	maven { url "https://maven.shedaniel.me/" }
	maven { url "https://maven.terraformersmc.com/" }
	maven { url "https://api.modrinth.com/maven" }
	maven { url "https://libs.azuredoom.com:4443/mods" }

	maven {
		url = 'https://maven.cafeteria.dev'
		content {
			includeGroup 'net.adriantodt.fabricmc'
		}
	}
	maven {
		url "https://maven.jamieswhiteshirt.com/libs-release"
		content {
			includeGroup "com.jamieswhiteshirt"
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	modImplementation "com.github.apace100:origins-fabric:${project.origins_version}"
	modImplementation "maven.modrinth:medieval-origins-revival:${project.medieval_version}"
	modImplementation "maven.modrinth:spell-power:${project.spell_power_version}"
	modImplementation "maven.modrinth:origin-furs:${project.origin_furs_version}"
	modImplementation "mod.azure.azurelib:azurelib-fabric-1.20.1:${project.azurelib_version}"

	modApi("com.github.Virtuoel:Pehkui:${project.pehkui_version}", {
		exclude group: "net.fabricmc.fabric-api"
	})
}
```

Log:
```
[15:59:15] [main/INFO] (FabricLoader/GameProvider) Loading Minecraft 1.20.1 with Fabric Loader 0.15.11
[15:59:16] [main/INFO] (FabricLoader) Loading 76 mods:
	- additionalentityattributes 1.3.0+1.20.0
	- apoli 2.9.0
	- azurelib 2.0.222
	- calio 1.11.0
	- cardinal-components-base 5.2.1
	- cardinal-components-entity 5.2.1
	- cloth-basic-math 0.6.1
	- cloth-config 11.0.99
	- esoteric-powers 0.0.1
	- fabric-api 0.92.1+1.20.1
	- fabric-api-base 0.4.31+1802ada577
	- fabric-api-lookup-api-v1 1.6.36+1802ada577
	- fabric-biome-api-v1 13.0.13+1802ada577
	- fabric-block-api-v1 1.0.11+1802ada577
	- fabric-block-view-api-v2 1.0.1+1802ada577
	- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	- fabric-client-tags-api-v1 1.1.2+1802ada577
	- fabric-command-api-v1 1.2.34+f71b366f77
	- fabric-command-api-v2 2.2.13+1802ada577
	- fabric-commands-v0 0.2.51+df3654b377
	- fabric-containers-v0 0.1.64+df3654b377
	- fabric-content-registries-v0 4.0.11+1802ada577
	- fabric-convention-tags-v1 1.5.5+1802ada577
	- fabric-crash-report-info-v1 0.2.19+1802ada577
	- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	- fabric-data-generation-api-v1 12.3.4+1802ada577
	- fabric-dimensions-v1 2.1.54+1802ada577
	- fabric-entity-events-v1 1.6.0+1c78457f77
	- fabric-events-interaction-v0 0.6.2+1802ada577
	- fabric-events-lifecycle-v0 0.2.63+df3654b377
	- fabric-game-rule-api-v1 1.0.40+1802ada577
	- fabric-gametest-api-v1 1.2.13+1802ada577
	- fabric-item-api-v1 2.1.28+1802ada577
	- fabric-item-group-api-v1 4.0.12+1802ada577
	- fabric-key-binding-api-v1 1.0.37+1802ada577
	- fabric-keybindings-v0 0.2.35+df3654b377
	- fabric-lifecycle-events-v1 2.2.22+1802ada577
	- fabric-loot-api-v2 1.2.1+1802ada577
	- fabric-loot-tables-v1 1.1.45+9e7660c677
	- fabric-message-api-v1 5.1.9+1802ada577
	- fabric-mining-level-api-v1 2.1.50+1802ada577
	- fabric-model-loading-api-v1 1.0.3+1802ada577
	- fabric-models-v0 0.4.2+9386d8a777
	- fabric-networking-api-v1 1.3.11+1802ada577
	- fabric-networking-v0 0.3.51+df3654b377
	- fabric-object-builder-api-v1 11.1.3+1802ada577
	- fabric-particles-v1 1.1.2+1802ada577
	- fabric-recipe-api-v1 1.0.21+1802ada577
	- fabric-registry-sync-v0 2.3.3+1802ada577
	- fabric-renderer-api-v1 3.2.1+1802ada577
	- fabric-renderer-indigo 1.5.1+1802ada577
	- fabric-renderer-registries-v1 3.2.46+df3654b377
	- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	- fabric-rendering-fluids-v1 3.0.28+1802ada577
	- fabric-rendering-v0 1.1.49+df3654b377
	- fabric-rendering-v1 3.0.8+1802ada577
	- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	- fabric-resource-loader-v0 0.11.10+1802ada577
	- fabric-screen-api-v1 2.0.8+1802ada577
	- fabric-screen-handler-api-v1 1.3.30+1802ada577
	- fabric-sound-api-v1 1.0.13+1802ada577
	- fabric-transfer-api-v1 3.3.5+8dd72ea377
	- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabricloader 0.15.11
	- java 17
	- kanos_config 0.4.1+1.14.4-1.19.4
	- medievalorigins 6.3.6+1.20.1
	- minecraft 1.20.1
	- mixinextras 0.3.5
	- modmenu 7.2.2
	- originfur 1.0.10
	- origins 1.10.0
	- pehkui 3.8.1+1.14.4-1.20.6
	- playerabilitylib 1.8.0
	- reach-entity-attributes 2.4.0
	- spell_power 0.10.2+1.20.1
[15:59:16] [main/INFO] (FabricLoader/Mixin) SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/gears/.gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/9527e6b0d2449408958fd1302594dc65ec5ade9c/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[15:59:16] [main/INFO] (FabricLoader/Mixin) Loaded Fabric development mappings for mixin remapper!
[15:59:16] [main/INFO] (FabricLoader/Mixin) Compatibility level set to JAVA_16
[15:59:16] [main/INFO] (FabricLoader/Mixin) Compatibility level set to JAVA_17
[15:59:17] [main/INFO] (FabricLoader/MixinExtras|Service) Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[15:59:20] [main/ERROR] (FabricLoader) Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: net/tinyconfig/ConfigManager
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/tinyconfig/ConfigManager
	at net.spell_power.SpellPowerMod.<clinit>(SpellPowerMod.java:18) ~[spell-power-0.10.2+1.20.1.jar:?]
	at net.minecraft.entity.attribute.EntityAttributes.handler$bhc000$spell_power$static_tail_SpellPower(EntityAttributes.java:514) ~[minecraft-merged-0b51391e04-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.entity.attribute.EntityAttributes.<clinit>(EntityAttributes.java:20) ~[minecraft-merged-0b51391e04-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.entity.effect.StatusEffects.<clinit>(StatusEffects.java:15) ~[minecraft-merged-0b51391e04-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.block.Blocks.<clinit>(Blocks.java:291) ~[minecraft-merged-0b51391e04-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.block.FireBlock.registerDefaultFlammables(FireBlock.java:326) ~[minecraft-merged-0b51391e04-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap.java:54) ~[minecraft-merged-0b51391e04-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[minecraft-merged-0b51391e04-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 3 more
Caused by: java.lang.ClassNotFoundException: net.tinyconfig.ConfigManager
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.spell_power.SpellPowerMod.<clinit>(SpellPowerMod.java:18) ~[spell-power-0.10.2+1.20.1.jar:?]
	at net.minecraft.entity.attribute.EntityAttributes.handler$bhc000$spell_power$static_tail_SpellPower(EntityAttributes.java:514) ~[minecraft-merged-0b51391e04-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.entity.attribute.EntityAttributes.<clinit>(EntityAttributes.java:20) ~[minecraft-merged-0b51391e04-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.entity.effect.StatusEffects.<clinit>(StatusEffects.java:15) ~[minecraft-merged-0b51391e04-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.block.Blocks.<clinit>(Blocks.java:291) ~[minecraft-merged-0b51391e04-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.block.FireBlock.registerDefaultFlammables(FireBlock.java:326) ~[minecraft-merged-0b51391e04-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap.java:54) ~[minecraft-merged-0b51391e04-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[minecraft-merged-0b51391e04-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 3 more
```

Edit:
Manually adding TinyConfig as a dependency fixed it. So maybe the readme for developers should be updated to include it as well.

**Comment by ZsoltMolnarrr** [comment]
Could you show how exactly you added TinyConfig manually?

**Comment by A5ho9999** [comment]
Just by the instructions provided on the [GitHub](https://github.com/ZsoltMolnarrr/TinyConfig?tab=readme-ov-file#installation) page

**Comment by ZsoltMolnarrr** [comment]
I set TinyConfig to be included in the SpellPower jar.
Do you have any idea how the problem could be fixed on my end?

**Comment by A5ho9999** [comment]
I would have no idea sorry
